### ISSUE TITLE
Hardware cannot set color space "YCbCr444"

### ISSUE THREAD

**Issue by NerdyShawn** [tolga9009/elgato-gchd#18]
On ubuntu 14.04 on an Asus G75VW with Nvidia GTX 660M, updated to latest Nvidia Drivers 361.42. I cannot adjust the "color space" as you suggest to get rid of the green tint to the image(I only have RGB value). This might be a hardware limitation of my system, potentially GPU or Laptop display is the issue I think, referencing FreeBSD docs. Just wanted to share, not necessarily looking for a fix.

ftp://download.nvidia.com/XFree86/FreeBSD-x86/304.32/README/README.txt

"YCbCr444": sets color space to YCbCr 4:4:4. YCbCr supports only
         limited color range. It is not possible to set this color space if
         the GPU or display is not capable of limited range.
    
    
    If the ColorSpace option is not specified, or is incorrectly specified,
    then the color space is set to RGB by default.

**Comment by tolga9009** [comment]
This is also true for my monitor, HP ZR22W. However, you can set color space per display. So, you can e.g. set YCbCr for the Elgato GCHD and RGB for your monitor, if you have them both connected at the same time.

Or, you can set your Elgato GCHD to YCbCr and let Elgato's HDMI-Out (which isn't a 1:1 HDMI-passthrough btw.) handle your monitor.

However, since the green tint issue is finally fixed (not published yet), this won't be an issue anymore.

**Comment by tolga9009** [comment]
Closing this issue, since the original issue #8 has been fixed. You can now switch colorspaces using `-c rgb` or `-c yuv`, according to your source. More information can be found in the original issue.
