### ISSUE TITLE
Unable to build (Mac 10.11.6)

### ISSUE THREAD

**Issue by JoshuaCarroll** [tolga9009/elgato-gchd#21]
I was following the instructions to build this on my Mac, but I am getting an error message when I run `cmake ..` from the build directory.

I am running Mac 10.11.6. Please let me know if you additional system details. Here is the error message:

```
Joshuas-MBP:build joshuacarroll$ cmake ..
CMake Error at /usr/local/Cellar/cmake/3.6.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.6.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.6.1/share/cmake/Modules/FindPkgConfig.cmake:49 (find_package_handle_standard_args)
  src/CMakeLists.txt:1 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/Users/joshuacarroll/Documents/Github/elgato-gchd/build/CMakeFiles/CMakeOutput.log".
```

**Comment by JoshuaCarroll** [comment]
I needed to install pkg-config.  Now I have a different error when I run `make`.

```
Joshuas-MBP:build joshuacarroll$ make
[  4%] Building CXX object src/CMakeFiles/gchd.dir/disk.cpp.o
error: unable to open output file 'CMakeFiles/gchd.dir/disk.cpp.o': 'Permission denied'
1 error generated.
make[2]: *** [src/CMakeFiles/gchd.dir/disk.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/gchd.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by tolga9009** [comment]
Thanks for posting this issue! I guess we need to write a good tutorial for Mac OS X. I've also experienced a rough building process on Mac OS X, unfortunately my aged brain can't deliver the details anymore.

I'm not too familiar with Mac OS X building environment, but I would suggest you to fix the `Permission denied` issue by using `sudo make` instead of `make`. This should bring you one step closer. Please let us know, if any other error messages show up. We can use them to write the Mac OS X guide.

Cheers,
Tolga

**Comment by JoshuaCarroll** [comment]
I had already tried running as su before I opened the issue.  However I walked away from this while busy with other projects and I no longer have this error.  I have a different error message, so I'll open a different issue and close this one.
