### ISSUE TITLE
OSX make: 'libusb-1.0/libusb.h' file not found

### ISSUE THREAD

**Issue by JoshuaCarroll** [tolga9009/elgato-gchd#22]
Attempting to follow the building instructions on Mac. During make, I get `'libusb-1.0/libusb.h' file not found`

```
$ make
Scanning dependencies of target gchd
[  4%] Building CXX object src/CMakeFiles/gchd.dir/disk.cpp.o
In file included from /Users/joshuacarroll/documents/Github/elgato-gchd/src/disk.cpp:10:
In file included from /Users/joshuacarroll/documents/Github/elgato-gchd/src/disk.hpp:15:
/Users/joshuacarroll/documents/Github/elgato-gchd/src/gchd.hpp:15:10: fatal error: 'libusb-1.0/libusb.h' file not found
#include <libusb-1.0/libusb.h>
         ^
1 error generated.
make[2]: *** [src/CMakeFiles/gchd.dir/disk.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/gchd.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by JoshuaCarroll** [comment]
I'm not familiar enough with make to edit your files to accommodate this, but I copied the libusb.h into the src directory and it got past that error.

```
cp /usr/local/include/libusb-1.0 ~/Documents/Github/elgato-gchd/src/
```

I'll leave this open for the project owner to decide if and how to address this.

**Comment by tolga9009** [comment]
Thanks for reporting, it looks like libusb-1.0 didn't got installed system-wide. I'm not sure, what exactly causes this, but I remember stumbling on the same issue(s) aswell. Unfortunately, I don't have OS X anymore.

However, it looks like KVM improved in terms of OS X. I need to know, whether this is due to a technical issue, or rather due to poor documentation.
