### ISSUE TITLE
Live capture

### ISSUE THREAD

**Issue by Gotos** [tolga9009/elgato-gchd#4]
I'd love to stream games with my GCHD without having to boot windows. Unfortunately your software captures to a file. If I open that file with VLC, it will start playing that file from the beginning. Even if I try to skip to the end of the file I will have a delay of about 3 seconds, which is to much to play fast-paced games. Will it be possible to "stream" the video directly to VLC to reduce the delay in a future version? Maybe via faking a standard video-/audio-device or by playing the video within the software?

**Comment by tolga9009** [comment]
Yes, this is currently a top priority feature. There is a special library for this, called V4L2. It is a library to create video devices (like /dev/video0) and stream videos. However, it is the first time I'm gonna use that library and I'm surely gonna need to do lots of homework and read documentations about it, as I'm just a hobby-programmer.

But the underlying structure is basically done: the driver is receiving video and audio stream via USB, puts them into a buffer and writes it to a file. Instead of writing it to a file, we can pass it to a V4L2 device. This is the theory at least. We'll see, if it works.

The same here: I currently have no time to work on these drivers. I will pick up the work in about 3 - 4 weeks.

Cheers,
Tolga

**Comment by tolga9009** [comment]
Okay, I had some time to look into this and read the documentations about V4L2. V4L2 will "not" work for this user space driver, as it is designed for kernel space.

What is currently working as a trade-off: writing to a file and using OBS Studio to stream this file. There will be some delay though and currently, only 720p will work as an input. Also, you will need a large harddrive, as the file will grow, depending on how long you're streaming. Maybe, I could improve this code, so the file won't infinitely grow, but keep within a fixed filesize limit: once the filesize limit is reached, the oldest frame / data would get deleted, so there is room for new data.

To get proper V4L2 support done, we need to port this over to kernel space. However, in it's current state, this code is not ready to be ported over to kernel space, as there is tons of stuff to be found out and done. So, this project will primarily serve to learn more about the device and to try things out.

Cheers,
Tolga

**Comment by tolga9009** [comment]
Hi there,

with commit 3db79e1, the delay has been reduced significantly. The program will now write to a temporary FIFO pipe, which can be found under `/tmp/elgato_gchd.ts`. This file can now be opened with VLC and be used to live capture. Please note, that there is still a slight delay of around 1s - 2s, which also can be found in the Windows and Mac versions of the driver. Also, for some reason, the FIFO pipe doesn't work with OBS Studio.

Closing this issue now. Thanks for sharing your ideas!

Cheers,
Tolga
