### ISSUE TITLE
Analogue input

### ISSUE THREAD

**Issue by DaGump** [tolga9009/elgato-gchd#9]
Is there any way to use the analogue input of the Elgato HD?

**Comment by tolga9009** [comment]
Currently, there is no possibility to use analogue input. I have done no research about analogue input, so I have no idea about how it actually works. It's not a feature I'm working on at the moment, I'm sorry.

**Comment by DaGump** [comment]
Too bad ... I hope it's just a slight change in the configuration since it is essential to my project. In case I figure it out, I'll let you know.

**Comment by tolga9009** [comment]
I would like to keep this issue open, until we have implemented analog input. I was mentioning, that it's not a feature I'm currently working on, but it's definitely a feature I want to add, as soon as I'm making progress. My next long and hopefully productive development session will begin on 17 December.

I have thought about analog input these days. It's difficult to capture 720p or 1080p footage, because the buffer of my USB analyzer gets flooded and traffic gets lost. I'm able to capture about ~10 seconds of traffic for 720p material and roughly half of that for 1080p material. While this is totally fine for capturing the setup sequence and parts of the bulk transfer, it is not enough to capture the halt / idle signal. Capturing analog input might give me more time, so I can look into the idle sequence.

**Comment by LRFLEW** [comment]
> It's difficult to capture 720p or 1080p footage, because the buffer of my USB analyzer gets flooded and traffic gets lost.

This is actually something I think could actually be worked around. We know what the three massive data-transfers are (uploading the two firmwares and the ts stream). At this point, all we care about are the control messages. Does your analyzer support only capturing the specific packet types? If so, that could resolve the issue of not being able to capture all the data.

I'm also willing to work on this. I don't have a USB capture device, but I did get the software solution to work (I think). I also have a feeling that disassembling the software Elgato provides might reveal some secrets. While very unlikely, I think that it might be possible to use the firmware dumps to get some insight as well (that is if we can figure out what version of ARM is being used).

**Comment by tolga9009** [comment]
> This is actually something I think could actually be worked around. We know what the three massive data-transfers are (uploading the two firmwares and the ts stream). At this point, all we care about are the control messages.

I don't consider the firmware uploads as "massive", as they are in the range of some kilobytes. The major amount of traffic is generated by the bulk transfers. And I also think that PING and NAK packets are also generating a huge amount of traffic for my USB analyzer. They might be small packets by themselves, but I've already seen tens and hundreds of thousands of them between 2 sequences. It seems to be a software problem, but noone has worked on OpenVizsla for quite some time now (https://github.com/openvizsla/ov_ftdi).

> Does your analyzer support only capturing the specific packet types? If so, that could resolve the issue of not being able to capture all the data.

Unfortunately, no. The hardware / software isn't advanced enough to do that. jedahan has written a script for me to filter out irrelevant stuff (https://github.com/jedahan/openvizsla2c) and I have ported that script over to C++ and improved it (I've just noticed, that I haven't uploaded it to GitHub yet). But these scripts can only be used after capturing USB traffic. I think we would need to mess around with OpenVizsla's Python script, in order to filter out unneeded stuff / do some profiling and find out the weak spots.

My research about the OpenVizsla USB analyzer showed me, that my particular setup peaks out at about 10 MB/s. I've been told by the OpenVizsla developers, that this is probably due to some limitations in their software implementation / Python script. According to USB 2.0 High-Speed specs, 30 MB/s should be possible. I assume the Elgato needs around 20 - 30 MB/s.

**Comment by tolga9009** [comment]
Since most of the stuff is already implemented, I'm working on this next. Any specific setup, I should use?

**Comment by Glog78** [comment]
Is this composite input restricted to 576i ? I'm using composite 1080i easiest way for the ps3

**Comment by tolga9009** [comment]
I'm just in the process of doing 1080i60 and 720p60 right now, will be available within the next hour! Composite is restricted to 576i50 PAL at the moment, I will be working on NTSC next hacking session. Component currently supports 576p50 and 1080p30.

**Comment by Glog78** [comment]
Than it might use component / let me check the settings :)

**Comment by Glog78** [comment]
Yeah might be component.

**Comment by tolga9009** [comment]
Pushed out 1080i60 now b2d3deb0d804a585c234a0b932308c8d79a1207c. Please use the following command: `sudo ./elgato-gchd -r c1080i`. The `c` in `c1080i` stands for component. I will change command-line options next big update. But for now, this will do fine. Updating readme next.

**Comment by Glog78** [comment]
for my pal ps3 everything seem to run :) next enhancment automatic resolution detection :+1:

**Comment by tolga9009** [comment]
Thanks for testing, I'm closing this issue.
